export { default as CourseDetailPage } from './course-detail-page'
export { default as CourseHeader } from './components/course-header'
export { default as CourseTabs } from './components/course-tabs'
export { default as CourseAboutTab } from './components/course-about-tab'
export { default as CourseProfessorsTab } from './components/course-professors-tab'
export { default as CourseAdmissionTab } from './components/course-admission-tab'
export { default as CourseFAQTab } from './components/course-faq-tab'
export * from './hooks/use-course-data'
export * from './mock/course-detail-mock'
