/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

const metadata = {
  models: {
    user: {
      name: 'User',
      fields: {
        id: {
          name: 'id',
          type: 'String',
          isId: true,
          attributes: [{ name: '@default', args: [] }],
        },
        createdAt: {
          name: 'createdAt',
          type: 'DateTime',
          attributes: [{ name: '@default', args: [] }],
        },
        updatedAt: {
          name: 'updatedAt',
          type: 'DateTime',
          attributes: [{ name: '@updatedAt', args: [] }],
        },
        email: {
          name: 'email',
          type: 'String',
        },
        password: {
          name: 'password',
          type: 'String',
        },
        name: {
          name: 'name',
          type: 'String',
          isOptional: true,
        },
        role: {
          name: 'role',
          type: 'Role',
          attributes: [{ name: '@default', args: [] }],
        },
        professor: {
          name: 'professor',
          type: 'Professor',
          isDataModel: true,
          isOptional: true,
          backLink: 'user',
        },
      },
      uniqueConstraints: {
        id: {
          name: 'id',
          fields: ['id'],
        },
        email: {
          name: 'email',
          fields: ['email'],
        },
      },
    },
    course: {
      name: 'Course',
      fields: {
        id: {
          name: 'id',
          type: 'String',
          isId: true,
          attributes: [{ name: '@default', args: [] }],
        },
        createdAt: {
          name: 'createdAt',
          type: 'DateTime',
          attributes: [{ name: '@default', args: [] }],
        },
        updatedAt: {
          name: 'updatedAt',
          type: 'DateTime',
          attributes: [{ name: '@updatedAt', args: [] }],
        },
        name: {
          name: 'name',
          type: 'String',
        },
        professors: {
          name: 'professors',
          type: 'Professor',
          isDataModel: true,
          isArray: true,
          backLink: 'courses',
          isRelationOwner: true,
        },
      },
      uniqueConstraints: {
        id: {
          name: 'id',
          fields: ['id'],
        },
        name: {
          name: 'name',
          fields: ['name'],
        },
      },
    },
    professor: {
      name: 'Professor',
      fields: {
        id: {
          name: 'id',
          type: 'String',
          isId: true,
          attributes: [{ name: '@default', args: [] }],
        },
        createdAt: {
          name: 'createdAt',
          type: 'DateTime',
          attributes: [{ name: '@default', args: [] }],
        },
        updatedAt: {
          name: 'updatedAt',
          type: 'DateTime',
          attributes: [{ name: '@updatedAt', args: [] }],
        },
        courses: {
          name: 'courses',
          type: 'Course',
          isDataModel: true,
          isArray: true,
          backLink: 'professors',
          isRelationOwner: true,
        },
        summary: {
          name: 'summary',
          type: 'String',
          isOptional: true,
        },
        specialties: {
          name: 'specialties',
          type: 'String',
          isArray: true,
        },
        image: {
          name: 'image',
          type: 'String',
          isOptional: true,
        },
        researchAreas: {
          name: 'researchAreas',
          type: 'String',
          isArray: true,
        },
        officeHours: {
          name: 'officeHours',
          type: 'String',
          isOptional: true,
        },
        lattes: {
          name: 'lattes',
          type: 'String',
          isOptional: true,
        },
        publications: {
          name: 'publications',
          type: 'Publication',
          isTypeDef: true,
          isArray: true,
        },
        researchProjects: {
          name: 'researchProjects',
          type: 'ResearchProject',
          isTypeDef: true,
          isArray: true,
        },
        extensionProjects: {
          name: 'extensionProjects',
          type: 'ExtensionProject',
          isTypeDef: true,
          isArray: true,
        },
        userId: {
          name: 'userId',
          type: 'String',
          isForeignKey: true,
          relationField: 'user',
        },
        user: {
          name: 'user',
          type: 'User',
          isDataModel: true,
          backLink: 'professor',
          isRelationOwner: true,
          foreignKeyMapping: { id: 'userId' },
        },
      },
      uniqueConstraints: {
        id: {
          name: 'id',
          fields: ['id'],
        },
        userId: {
          name: 'userId',
          fields: ['userId'],
        },
      },
    },
  },
  typeDefs: {
    publication: {
      name: 'Publication',
      fields: {
        title: {
          name: 'title',
          type: 'String',
        },
        authors: {
          name: 'authors',
          type: 'String',
          isArray: true,
        },
        date: {
          name: 'date',
          type: 'DateTime',
        },
        link: {
          name: 'link',
          type: 'String',
          isOptional: true,
        },
      },
    },
    researchProject: {
      name: 'ResearchProject',
      fields: {
        title: {
          name: 'title',
          type: 'String',
        },
        startDate: {
          name: 'startDate',
          type: 'DateTime',
        },
        endDate: {
          name: 'endDate',
          type: 'DateTime',
          isOptional: true,
        },
        status: {
          name: 'status',
          type: 'ProjectStatus',
        },
        description: {
          name: 'description',
          type: 'String',
          isOptional: true,
        },
      },
    },
    extensionProject: {
      name: 'ExtensionProject',
      fields: {
        title: {
          name: 'title',
          type: 'String',
        },
        startDate: {
          name: 'startDate',
          type: 'DateTime',
        },
        status: {
          name: 'status',
          type: 'ProjectStatus',
        },
        endDate: {
          name: 'endDate',
          type: 'DateTime',
          isOptional: true,
        },
        description: {
          name: 'description',
          type: 'String',
          isOptional: true,
        },
      },
    },
  },
  deleteCascade: {
    user: ['Professor'],
  },
  authModel: 'User',
}
export default metadata
