/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, Attachment } from '@zenstackhq/runtime/models'
import type {
  UseMutationOptions,
  UseQueryOptions,
  UseInfiniteQueryOptions,
  InfiniteData,
} from '@tanstack/react-query'
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react'
import {
  useModelQuery,
  useInfiniteModelQuery,
  useModelMutation,
} from '@zenstackhq/tanstack-query/runtime-v5/react'
import type {
  PickEnumerable,
  CheckSelect,
  QueryError,
  ExtraQueryOptions,
  ExtraMutationOptions,
} from '@zenstackhq/tanstack-query/runtime-v5'
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta'
type DefaultError = QueryError
import {
  useSuspenseModelQuery,
  useSuspenseInfiniteModelQuery,
} from '@zenstackhq/tanstack-query/runtime-v5/react'
import type {
  UseSuspenseQueryOptions,
  UseSuspenseInfiniteQueryOptions,
} from '@tanstack/react-query'

export function useCreateAttachment(
  options?: Omit<
    UseMutationOptions<
      Attachment | undefined,
      DefaultError,
      Prisma.AttachmentCreateArgs
    > &
      ExtraMutationOptions,
    'mutationFn'
  >,
) {
  const { endpoint, fetch } = getHooksContext()
  const _mutation = useModelMutation<
    Prisma.AttachmentCreateArgs,
    DefaultError,
    Attachment,
    true
  >(
    'Attachment',
    'POST',
    `${endpoint}/attachment/create`,
    metadata,
    options,
    fetch,
    true,
  )
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AttachmentCreateArgs>(
      args: Prisma.SelectSubset<T, Prisma.AttachmentCreateArgs>,
      options?: Omit<
        UseMutationOptions<
          | CheckSelect<T, Attachment, Prisma.AttachmentGetPayload<T>>
          | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.AttachmentCreateArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >,
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as
        | CheckSelect<T, Attachment, Prisma.AttachmentGetPayload<T>>
        | undefined
    },
  }
  return mutation
}

export function useCreateManyAttachment(
  options?: Omit<
    UseMutationOptions<
      Prisma.BatchPayload,
      DefaultError,
      Prisma.AttachmentCreateManyArgs
    > &
      ExtraMutationOptions,
    'mutationFn'
  >,
) {
  const { endpoint, fetch } = getHooksContext()
  const _mutation = useModelMutation<
    Prisma.AttachmentCreateManyArgs,
    DefaultError,
    Prisma.BatchPayload,
    false
  >(
    'Attachment',
    'POST',
    `${endpoint}/attachment/createMany`,
    metadata,
    options,
    fetch,
    false,
  )
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AttachmentCreateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.AttachmentCreateManyArgs>,
      options?: Omit<
        UseMutationOptions<
          Prisma.BatchPayload,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.AttachmentCreateManyArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >,
    ) => {
      return (await _mutation.mutateAsync(
        args,
        options as any,
      )) as Prisma.BatchPayload
    },
  }
  return mutation
}

export function useFindManyAttachment<
  TArgs extends Prisma.AttachmentFindManyArgs,
  TQueryFnData = Array<
    Prisma.AttachmentGetPayload<TArgs> & { $optimistic?: boolean }
  >,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.AttachmentFindManyArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/findMany`,
    args,
    options,
    fetch,
  )
}

export function useInfiniteFindManyAttachment<
  TArgs extends Prisma.AttachmentFindManyArgs,
  TQueryFnData = Array<Prisma.AttachmentGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.AttachmentFindManyArgs>,
  options?: Omit<
    UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>,
    'queryKey' | 'initialPageParam'
  >,
) {
  options = options ?? { getNextPageParam: () => null }
  const { endpoint, fetch } = getHooksContext()
  return useInfiniteModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/findMany`,
    args,
    options,
    fetch,
  )
}

export function useSuspenseFindManyAttachment<
  TArgs extends Prisma.AttachmentFindManyArgs,
  TQueryFnData = Array<
    Prisma.AttachmentGetPayload<TArgs> & { $optimistic?: boolean }
  >,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.AttachmentFindManyArgs>,
  options?: Omit<
    UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
    'queryKey'
  > &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/findMany`,
    args,
    options,
    fetch,
  )
}

export function useSuspenseInfiniteFindManyAttachment<
  TArgs extends Prisma.AttachmentFindManyArgs,
  TQueryFnData = Array<Prisma.AttachmentGetPayload<TArgs>>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.AttachmentFindManyArgs>,
  options?: Omit<
    UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>,
    'queryKey' | 'initialPageParam'
  >,
) {
  options = options ?? { getNextPageParam: () => null }
  const { endpoint, fetch } = getHooksContext()
  return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/findMany`,
    args,
    options,
    fetch,
  )
}

export function useFindUniqueAttachment<
  TArgs extends Prisma.AttachmentFindUniqueArgs,
  TQueryFnData = Prisma.AttachmentGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.AttachmentFindUniqueArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/findUnique`,
    args,
    options,
    fetch,
  )
}

export function useSuspenseFindUniqueAttachment<
  TArgs extends Prisma.AttachmentFindUniqueArgs,
  TQueryFnData = Prisma.AttachmentGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.AttachmentFindUniqueArgs>,
  options?: Omit<
    UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
    'queryKey'
  > &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/findUnique`,
    args,
    options,
    fetch,
  )
}

export function useFindFirstAttachment<
  TArgs extends Prisma.AttachmentFindFirstArgs,
  TQueryFnData = Prisma.AttachmentGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.AttachmentFindFirstArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/findFirst`,
    args,
    options,
    fetch,
  )
}

export function useSuspenseFindFirstAttachment<
  TArgs extends Prisma.AttachmentFindFirstArgs,
  TQueryFnData = Prisma.AttachmentGetPayload<TArgs> & { $optimistic?: boolean },
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.AttachmentFindFirstArgs>,
  options?: Omit<
    UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
    'queryKey'
  > &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/findFirst`,
    args,
    options,
    fetch,
  )
}

export function useUpdateAttachment(
  options?: Omit<
    UseMutationOptions<
      Attachment | undefined,
      DefaultError,
      Prisma.AttachmentUpdateArgs
    > &
      ExtraMutationOptions,
    'mutationFn'
  >,
) {
  const { endpoint, fetch } = getHooksContext()
  const _mutation = useModelMutation<
    Prisma.AttachmentUpdateArgs,
    DefaultError,
    Attachment,
    true
  >(
    'Attachment',
    'PUT',
    `${endpoint}/attachment/update`,
    metadata,
    options,
    fetch,
    true,
  )
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AttachmentUpdateArgs>(
      args: Prisma.SelectSubset<T, Prisma.AttachmentUpdateArgs>,
      options?: Omit<
        UseMutationOptions<
          | CheckSelect<T, Attachment, Prisma.AttachmentGetPayload<T>>
          | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.AttachmentUpdateArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >,
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as
        | CheckSelect<T, Attachment, Prisma.AttachmentGetPayload<T>>
        | undefined
    },
  }
  return mutation
}

export function useUpdateManyAttachment(
  options?: Omit<
    UseMutationOptions<
      Prisma.BatchPayload,
      DefaultError,
      Prisma.AttachmentUpdateManyArgs
    > &
      ExtraMutationOptions,
    'mutationFn'
  >,
) {
  const { endpoint, fetch } = getHooksContext()
  const _mutation = useModelMutation<
    Prisma.AttachmentUpdateManyArgs,
    DefaultError,
    Prisma.BatchPayload,
    false
  >(
    'Attachment',
    'PUT',
    `${endpoint}/attachment/updateMany`,
    metadata,
    options,
    fetch,
    false,
  )
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AttachmentUpdateManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.AttachmentUpdateManyArgs>,
      options?: Omit<
        UseMutationOptions<
          Prisma.BatchPayload,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.AttachmentUpdateManyArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >,
    ) => {
      return (await _mutation.mutateAsync(
        args,
        options as any,
      )) as Prisma.BatchPayload
    },
  }
  return mutation
}

export function useUpsertAttachment(
  options?: Omit<
    UseMutationOptions<
      Attachment | undefined,
      DefaultError,
      Prisma.AttachmentUpsertArgs
    > &
      ExtraMutationOptions,
    'mutationFn'
  >,
) {
  const { endpoint, fetch } = getHooksContext()
  const _mutation = useModelMutation<
    Prisma.AttachmentUpsertArgs,
    DefaultError,
    Attachment,
    true
  >(
    'Attachment',
    'POST',
    `${endpoint}/attachment/upsert`,
    metadata,
    options,
    fetch,
    true,
  )
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AttachmentUpsertArgs>(
      args: Prisma.SelectSubset<T, Prisma.AttachmentUpsertArgs>,
      options?: Omit<
        UseMutationOptions<
          | CheckSelect<T, Attachment, Prisma.AttachmentGetPayload<T>>
          | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.AttachmentUpsertArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >,
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as
        | CheckSelect<T, Attachment, Prisma.AttachmentGetPayload<T>>
        | undefined
    },
  }
  return mutation
}

export function useDeleteAttachment(
  options?: Omit<
    UseMutationOptions<
      Attachment | undefined,
      DefaultError,
      Prisma.AttachmentDeleteArgs
    > &
      ExtraMutationOptions,
    'mutationFn'
  >,
) {
  const { endpoint, fetch } = getHooksContext()
  const _mutation = useModelMutation<
    Prisma.AttachmentDeleteArgs,
    DefaultError,
    Attachment,
    true
  >(
    'Attachment',
    'DELETE',
    `${endpoint}/attachment/delete`,
    metadata,
    options,
    fetch,
    true,
  )
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AttachmentDeleteArgs>(
      args: Prisma.SelectSubset<T, Prisma.AttachmentDeleteArgs>,
      options?: Omit<
        UseMutationOptions<
          | CheckSelect<T, Attachment, Prisma.AttachmentGetPayload<T>>
          | undefined,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.AttachmentDeleteArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >,
    ) => {
      return (await _mutation.mutateAsync(args, options as any)) as
        | CheckSelect<T, Attachment, Prisma.AttachmentGetPayload<T>>
        | undefined
    },
  }
  return mutation
}

export function useDeleteManyAttachment(
  options?: Omit<
    UseMutationOptions<
      Prisma.BatchPayload,
      DefaultError,
      Prisma.AttachmentDeleteManyArgs
    > &
      ExtraMutationOptions,
    'mutationFn'
  >,
) {
  const { endpoint, fetch } = getHooksContext()
  const _mutation = useModelMutation<
    Prisma.AttachmentDeleteManyArgs,
    DefaultError,
    Prisma.BatchPayload,
    false
  >(
    'Attachment',
    'DELETE',
    `${endpoint}/attachment/deleteMany`,
    metadata,
    options,
    fetch,
    false,
  )
  const mutation = {
    ..._mutation,
    mutateAsync: async <T extends Prisma.AttachmentDeleteManyArgs>(
      args: Prisma.SelectSubset<T, Prisma.AttachmentDeleteManyArgs>,
      options?: Omit<
        UseMutationOptions<
          Prisma.BatchPayload,
          DefaultError,
          Prisma.SelectSubset<T, Prisma.AttachmentDeleteManyArgs>
        > &
          ExtraMutationOptions,
        'mutationFn'
      >,
    ) => {
      return (await _mutation.mutateAsync(
        args,
        options as any,
      )) as Prisma.BatchPayload
    },
  }
  return mutation
}

export function useAggregateAttachment<
  TArgs extends Prisma.AttachmentAggregateArgs,
  TQueryFnData = Prisma.GetAttachmentAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.AttachmentAggregateArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/aggregate`,
    args,
    options,
    fetch,
  )
}

export function useSuspenseAggregateAttachment<
  TArgs extends Prisma.AttachmentAggregateArgs,
  TQueryFnData = Prisma.GetAttachmentAggregateType<TArgs>,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<TArgs, Prisma.AttachmentAggregateArgs>,
  options?: Omit<
    UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
    'queryKey'
  > &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/aggregate`,
    args,
    options,
    fetch,
  )
}

export function useGroupByAttachment<
  TArgs extends Prisma.AttachmentGroupByArgs,
  HasSelectOrTake extends Prisma.Or<
    Prisma.Extends<'skip', Prisma.Keys<TArgs>>,
    Prisma.Extends<'take', Prisma.Keys<TArgs>>
  >,
  OrderByArg extends Prisma.True extends HasSelectOrTake
    ? { orderBy: Prisma.AttachmentGroupByArgs['orderBy'] }
    : { orderBy?: Prisma.AttachmentGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<
    Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>
  >,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [
                  Error,
                  'Field ',
                  P,
                  ` in "having" needs to be provided in "by"`,
                ]
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.AttachmentGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs &
            keyof Prisma.AttachmentGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<
                  TArgs[P],
                  Prisma.AttachmentGroupByOutputType[P]
                >
            : Prisma.GetScalarType<
                TArgs[P],
                Prisma.AttachmentGroupByOutputType[P]
              >
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<
    TArgs,
    Prisma.SubsetIntersection<TArgs, Prisma.AttachmentGroupByArgs, OrderByArg> &
      InputErrors
  >,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/groupBy`,
    args,
    options,
    fetch,
  )
}

export function useSuspenseGroupByAttachment<
  TArgs extends Prisma.AttachmentGroupByArgs,
  HasSelectOrTake extends Prisma.Or<
    Prisma.Extends<'skip', Prisma.Keys<TArgs>>,
    Prisma.Extends<'take', Prisma.Keys<TArgs>>
  >,
  OrderByArg extends Prisma.True extends HasSelectOrTake
    ? { orderBy: Prisma.AttachmentGroupByArgs['orderBy'] }
    : { orderBy?: Prisma.AttachmentGroupByArgs['orderBy'] },
  OrderFields extends Prisma.ExcludeUnderscoreKeys<
    Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>
  >,
  ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>,
  ByValid extends Prisma.Has<ByFields, OrderFields>,
  HavingFields extends Prisma.GetHavingFields<TArgs['having']>,
  HavingValid extends Prisma.Has<ByFields, HavingFields>,
  ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False,
  InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
      ? {
          [P in HavingFields]: P extends ByFields
            ? never
            : P extends string
              ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
              : [
                  Error,
                  'Field ',
                  P,
                  ` in "having" needs to be provided in "by"`,
                ]
        }[HavingFields]
      : 'take' extends Prisma.Keys<TArgs>
        ? 'orderBy' extends Prisma.Keys<TArgs>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<TArgs>
          ? 'orderBy' extends Prisma.Keys<TArgs>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "skip", you also need to provide "orderBy"'
          : ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
              }[OrderFields],
  TQueryFnData = {} extends InputErrors
    ? Array<
        PickEnumerable<Prisma.AttachmentGroupByOutputType, TArgs['by']> & {
          [P in keyof TArgs &
            keyof Prisma.AttachmentGroupByOutputType]: P extends '_count'
            ? TArgs[P] extends boolean
              ? number
              : Prisma.GetScalarType<
                  TArgs[P],
                  Prisma.AttachmentGroupByOutputType[P]
                >
            : Prisma.GetScalarType<
                TArgs[P],
                Prisma.AttachmentGroupByOutputType[P]
              >
        }
      >
    : InputErrors,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args: Prisma.SelectSubset<
    TArgs,
    Prisma.SubsetIntersection<TArgs, Prisma.AttachmentGroupByArgs, OrderByArg> &
      InputErrors
  >,
  options?: Omit<
    UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
    'queryKey'
  > &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/groupBy`,
    args,
    options,
    fetch,
  )
}

export function useCountAttachment<
  TArgs extends Prisma.AttachmentCountArgs,
  TQueryFnData = TArgs extends { select: any }
    ? TArgs['select'] extends true
      ? number
      : Prisma.GetScalarType<
          TArgs['select'],
          Prisma.AttachmentCountAggregateOutputType
        >
    : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.AttachmentCountArgs>,
  options?: Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/count`,
    args,
    options,
    fetch,
  )
}

export function useSuspenseCountAttachment<
  TArgs extends Prisma.AttachmentCountArgs,
  TQueryFnData = TArgs extends { select: any }
    ? TArgs['select'] extends true
      ? number
      : Prisma.GetScalarType<
          TArgs['select'],
          Prisma.AttachmentCountAggregateOutputType
        >
    : number,
  TData = TQueryFnData,
  TError = DefaultError,
>(
  args?: Prisma.SelectSubset<TArgs, Prisma.AttachmentCountArgs>,
  options?: Omit<
    UseSuspenseQueryOptions<TQueryFnData, TError, TData>,
    'queryKey'
  > &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useSuspenseModelQuery<TQueryFnData, TData, TError>(
    'Attachment',
    `${endpoint}/attachment/count`,
    args,
    options,
    fetch,
  )
}

export function useCheckAttachment<TError = DefaultError>(
  args: {
    operation: PolicyCrudKind
    where?: {
      id?: string
      name?: string
      dataUrl?: string
      mimeType?: string
      size?: number
    }
  },
  options?: Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> &
    ExtraQueryOptions,
) {
  const { endpoint, fetch } = getHooksContext()
  return useModelQuery<boolean, boolean, TError>(
    'Attachment',
    `${endpoint}/attachment/check`,
    args,
    options,
    fetch,
  )
}
