/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, BlockComponent } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateBlockComponent(options?: Omit<(UseMutationOptions<(BlockComponent | undefined), DefaultError, Prisma.BlockComponentCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlockComponentCreateArgs, DefaultError, BlockComponent, true>('BlockComponent', 'POST', `${endpoint}/blockComponent/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlockComponentCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlockComponentCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, BlockComponent, Prisma.BlockComponentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BlockComponentCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BlockComponent, Prisma.BlockComponentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyBlockComponent(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BlockComponentCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlockComponentCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('BlockComponent', 'POST', `${endpoint}/blockComponent/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlockComponentCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlockComponentCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BlockComponentCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyBlockComponent<TArgs extends Prisma.BlockComponentFindManyArgs, TQueryFnData = Array<Prisma.BlockComponentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlockComponentFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/findMany`, args, options, fetch);
}

export function useInfiniteFindManyBlockComponent<TArgs extends Prisma.BlockComponentFindManyArgs, TQueryFnData = Array<Prisma.BlockComponentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlockComponentFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/findMany`, args, options, fetch);
}

export function useSuspenseFindManyBlockComponent<TArgs extends Prisma.BlockComponentFindManyArgs, TQueryFnData = Array<Prisma.BlockComponentGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlockComponentFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyBlockComponent<TArgs extends Prisma.BlockComponentFindManyArgs, TQueryFnData = Array<Prisma.BlockComponentGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlockComponentFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/findMany`, args, options, fetch);
}

export function useFindUniqueBlockComponent<TArgs extends Prisma.BlockComponentFindUniqueArgs, TQueryFnData = Prisma.BlockComponentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.BlockComponentFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueBlockComponent<TArgs extends Prisma.BlockComponentFindUniqueArgs, TQueryFnData = Prisma.BlockComponentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.BlockComponentFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/findUnique`, args, options, fetch);
}

export function useFindFirstBlockComponent<TArgs extends Prisma.BlockComponentFindFirstArgs, TQueryFnData = Prisma.BlockComponentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlockComponentFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstBlockComponent<TArgs extends Prisma.BlockComponentFindFirstArgs, TQueryFnData = Prisma.BlockComponentGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlockComponentFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/findFirst`, args, options, fetch);
}

export function useUpdateBlockComponent(options?: Omit<(UseMutationOptions<(BlockComponent | undefined), DefaultError, Prisma.BlockComponentUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlockComponentUpdateArgs, DefaultError, BlockComponent, true>('BlockComponent', 'PUT', `${endpoint}/blockComponent/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlockComponentUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlockComponentUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, BlockComponent, Prisma.BlockComponentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BlockComponentUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BlockComponent, Prisma.BlockComponentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyBlockComponent(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BlockComponentUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlockComponentUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('BlockComponent', 'PUT', `${endpoint}/blockComponent/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlockComponentUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlockComponentUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BlockComponentUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertBlockComponent(options?: Omit<(UseMutationOptions<(BlockComponent | undefined), DefaultError, Prisma.BlockComponentUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlockComponentUpsertArgs, DefaultError, BlockComponent, true>('BlockComponent', 'POST', `${endpoint}/blockComponent/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlockComponentUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlockComponentUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, BlockComponent, Prisma.BlockComponentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BlockComponentUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BlockComponent, Prisma.BlockComponentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteBlockComponent(options?: Omit<(UseMutationOptions<(BlockComponent | undefined), DefaultError, Prisma.BlockComponentDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlockComponentDeleteArgs, DefaultError, BlockComponent, true>('BlockComponent', 'DELETE', `${endpoint}/blockComponent/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlockComponentDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlockComponentDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, BlockComponent, Prisma.BlockComponentGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.BlockComponentDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, BlockComponent, Prisma.BlockComponentGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyBlockComponent(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.BlockComponentDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.BlockComponentDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('BlockComponent', 'DELETE', `${endpoint}/blockComponent/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.BlockComponentDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.BlockComponentDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.BlockComponentDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateBlockComponent<TArgs extends Prisma.BlockComponentAggregateArgs, TQueryFnData = Prisma.GetBlockComponentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.BlockComponentAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateBlockComponent<TArgs extends Prisma.BlockComponentAggregateArgs, TQueryFnData = Prisma.GetBlockComponentAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.BlockComponentAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/aggregate`, args, options, fetch);
}

export function useGroupByBlockComponent<TArgs extends Prisma.BlockComponentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.BlockComponentGroupByArgs['orderBy'] } : { orderBy?: Prisma.BlockComponentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.BlockComponentGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.BlockComponentGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.BlockComponentGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.BlockComponentGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.BlockComponentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByBlockComponent<TArgs extends Prisma.BlockComponentGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.BlockComponentGroupByArgs['orderBy'] } : { orderBy?: Prisma.BlockComponentGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.BlockComponentGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.BlockComponentGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.BlockComponentGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.BlockComponentGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.BlockComponentGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/groupBy`, args, options, fetch);
}

export function useCountBlockComponent<TArgs extends Prisma.BlockComponentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.BlockComponentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlockComponentCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/count`, args, options, fetch);
}

export function useSuspenseCountBlockComponent<TArgs extends Prisma.BlockComponentCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.BlockComponentCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.BlockComponentCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('BlockComponent', `${endpoint}/blockComponent/count`, args, options, fetch);
}
import type { BlockType } from '@prisma/client';

export function useCheckBlockComponent<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; blockType?: BlockType; order?: number; pageId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('BlockComponent', `${endpoint}/blockComponent/check`, args, options, fetch);
}
