/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

export * from './user';
export * from './course';
export * from './news-category';
export * from './news';
export * from './professor';
export * from './faq-category';
export * from './faq-item';
export * from './content-block';
export * from './attachment';
export * from './management';
export * from './project';
export * from './section';
export * from './generic-page';
export * from './college-data';
export * from './log-entry';
export { getQueryKey } from '@zenstackhq/tanstack-query/runtime-v5';
export { Provider } from '@zenstackhq/tanstack-query/runtime-v5/react';
export { default as metadata } from './__model_meta';
